FROM nginx:1.25-alpine
COPY index.html /usr/share/nginx/html/index.html
COPY script.js /usr/share/nginx/html/script.js
COPY styles.css /usr/share/nginx/html/styles.css
COPY favicon.ico /usr/share/nginx/html/favicon.ico
COPY public/ /usr/share/nginx/html/public/
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 5000
